### ISSUE TITLE
main.css

### ISSUE THREAD

**Issue by goliatone** [goliatone/documentation-theme-core.io#16]
Is **main.css** the same as **core.io-website**'s **main.css**? if it's different, could we rename it? I like to have only one **main.css** per website :) 
I'm building the whole: website, core.io + documentation + api. Trying to make all paths work when the different projects they are bundled together.

**Comment by Anaibi** [comment]
@goliatone, as of now it's the same, and whatever css is specific of documentation is in style.css. The idea is to later clean main.css of any rules that don't affect this page (documentation).

**Comment by Anaibi** [comment]
closed by #31
